export * from "@/services/district/types";
export type {
  DistrictHospitalRow,
  DistrictStats,
  ComparisonRow,
  CapacityRow,
  ResourceSummaryRow,
  DoctorAvailabilityRow,
  OpdAnalyticsData,
  ReferralFlow,
  Announcement,
  DistrictSettings,
  DistrictReportType,
  DistrictAuditEvent,
  DistrictAuditAction,
  MapPoint,
  DepartmentPerformanceRow,
  CapacityStatus,
  DepartmentDateRange,
  DistrictFilters,
  ServiceAvailabilityRow,
  HospitalLoadStatus,
  OpdAnalyticsPeriod,
  DepartmentVolumeRow,
  DepartmentPerformanceRow,
  AnnouncementAudience,
};