"use client";

import { useState } from "react";
import type { TokenConfig } from "@/services/hospital-ops/types";
import { useOpsMutations } from "../hooks/useHospitalOps";
import { usePermissions } from "@/features/auth/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { inputCls, labelCls, hintCls } from "@/features/consultation/utils/classes";

function TokenConfigForm({ initial }: { initial: TokenConfig }) {
  const [draft, setDraft] = useState<TokenConfig>(initial);
  const [savedAt, setSavedAt] = useState<string | null>(null);
  const [prefixPreview, setPrefixPreview] = useState("C");
  const { saveTokenConfig, busy, error } = useOpsMutations();
  const { can } = usePermissions();
  const editable = can("MANAGE_QUEUE_CONFIG");

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        void (async () => {
          const result = await saveTokenConfig(draft);
          if (result) {
            setDraft({ ...result });
            setSavedAt(new Date().toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }));
          }
        })();
      }}
      className="flex max-w-xl flex-col gap-4"
    >
      <p className="text-sm text-ink-500">
        Tokens are generated by the backend service. The frontend never computes token numbers.
      </p>

      <label className="flex items-center justify-between gap-3 rounded-card border border-ink-200 bg-surface p-4 shadow-card">
        <span>
          <span className="block text-sm font-medium text-ink-900">Daily reset</span>
          <span className={hintCls}>Numbering restarts at 001 each day.</span>
        </span>
        <input
          type="checkbox"
          disabled={!editable}
          checked={draft.dailyReset}
          onChange={(e) => {
            setDraft({ ...draft, dailyReset: e.target.checked });
            setSavedAt(null);
          }}
        />
      </label>

      <div className="grid gap-3 sm:grid-cols-2">
        <label className="block">
          <span className={labelCls}>Token format preview</span>
          <input
            className={`${inputCls} font-mono uppercase`}
            maxLength={3}
            disabled={!editable}
            value={prefixPreview}
            onChange={(e) => setPrefixPreview(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ""))}
          />
          <span className={hintCls}>
            Preview:{" "}
            <strong className="font-mono">{`${prefixPreview || "C"}-${String(
              Math.min(draft.maxDailyTokens, 1)
            ).padStart(3, "0")}`}</strong>
          </span>
        </label>
        <label className="block">
          <span className={labelCls}>Maximum daily tokens</span>
          <input
            className={inputCls}
            type="number"
            min={1}
            max={999}
            disabled={!editable}
            value={draft.maxDailyTokens}
            onChange={(e) => {
              setDraft({ ...draft, maxDailyTokens: Number(e.target.value) || 0 });
              setSavedAt(null);
            }}
          />
          <span className={hintCls}>
            {draft.maxDailyTokens > 999
              ? "Must be 999 or fewer per department per day."
              : "Registration is blocked once this limit is reached."}
          </span>
        </label>
      </div>

      {!editable && (
        <p className="text-sm text-status-warning">
          Changing token behaviour requires additional authorization.
        </p>
      )}
      {error && (
        <p className="text-sm text-status-danger" role="alert">
          {error}
        </p>
      )}
      <div className="flex items-center gap-3 border-t border-ink-200 pt-4">
        <Button size="lg" type="submit" disabled={!editable || busy}>
          {busy ? "Saving..." : "Save Token Settings"}
        </Button>
        {savedAt && <p className="text-sm text-status-success">Saved at {savedAt}</p>}
      </div>
    </form>
  );
}

export function TokenSettingsForm({
  hospitalId,
  config,
  isLoading,
}: {
  hospitalId: string;
  config?: TokenConfig;
  isLoading: boolean;
}) {
  if (isLoading || !config) return <Skeleton className="h-48 w-full" />;
  return <TokenConfigForm key={`${hospitalId}:${config.maxDailyTokens}`} initial={{ ...config }} />;
}
