export type Permission =
  | "VIEW_STATE_ANALYTICS"
  | "VIEW_DISTRICT_HOSPITALS"
  | "VIEW_ALL_HOSPITALS"
  | "VIEW_QUEUE_ALERTS"
  | "VIEW_REPORTS"
  | "VIEW_PATIENT"
  | "VIEW_CLINICAL_RECORD"
  | "MANAGE_HOSPITAL"
  | "MANAGE_OPD"
  | "MANAGE_DOCTOR";
