import type { UserRole } from "./types/auth.types";

export type Permission =
  | "VIEW_OWN_PROFILE"
  | "VIEW_OWN_MEDICAL_HISTORY"
  | "VIEW_PATIENT"
  | "VIEW_MEDICAL_HISTORY"
  | "CREATE_ENCOUNTER"
  | "EDIT_ENCOUNTER"
  | "COMPLETE_ENCOUNTER"
  | "PRESCRIBE_MEDICATION"
  | "REQUEST_CORRECTION"
  | "ORDER_DIAGNOSTICS"
  | "VIEW_DIAGNOSTIC_RESULTS"
  | "REVIEW_DIAGNOSTIC_RESULTS"
  | "VIEW_LAB_DASHBOARD"
  | "VIEW_LAB_ORDERS"
  | "COLLECT_SAMPLES"
  | "ENTER_RESULTS"
  | "SUBMIT_RESULTS"
  | "FINALIZE_RESULTS"
  | "VERIFY_RESULTS"
  | "ACKNOWLEDGE_CRITICAL_RESULT"
  | "SCHEDULE_DIAGNOSTICS"
  | "PERFORM_DIAGNOSTIC_PROCEDURE"
  | "WRITE_DIAGNOSTIC_REPORT"
  | "VERIFY_DIAGNOSTIC_REPORT"
  | "VIEW_OWN_APPOINTMENTS"
  | "BOOK_APPOINTMENT"
  | "VIEW_APPOINTMENT_SCHEDULE"
  | "MANAGE_APPOINTMENTS"
  | "CHECK_IN_APPOINTMENT"
  | "MANAGE_SCHEDULING"
  | "VIEW_PHARMACY_DASHBOARD"
  | "VIEW_PHARMACY_QUEUE"
  | "DISPENSE_MEDICATION"
  | "VIEW_PHARMACY_INVENTORY"
  | "MANAGE_PHARMACY_STOCK"
  | "VIEW_QUEUE"
  | "CALL_PATIENT"
  | "MANAGE_OPD"
  | "MANAGE_DOCTOR"
  | "MANAGE_STAFF"
  | "MANAGE_DEPARTMENTS"
  | "MANAGE_SERVICES"
  | "MANAGE_QUEUE_CONFIG"
  | "ASSIGN_STAFF_ROLES"
  | "VIEW_OPERATIONAL_AUDIT"
  | "MANAGE_HOSPITAL"
  | "VIEW_REPORTS"
  | "VIEW_DISTRICT_DATA"
  | "VIEW_STATE_DATA"
  | "MANAGE_DISTRICT_SETTINGS"
  | "PUBLISH_ANNOUNCEMENTS"
   | "VIEW_DISTRICT_AUDIT"
   | "EXPORT_REPORTS"
   | "MANAGE_STATE_SETTINGS"
   | "PUBLISH_STATE_ANNOUNCEMENTS"
   | "VIEW_STATE_AUDIT"
   | "MANAGE_STATE_USERS"
   | "SCHEDULE_REPORTS"
   | "VIEW_SYSTEM_HEALTH"
   | "MANAGE_EMERGENCY_MODE"
   | "ASSESS_PRIORITY"
  | "REQUEST_OVERRIDE"
  | "APPROVE_OVERRIDE"
  | "VIEW_PRIORITY_AUDIT"
  | "REQUEST_ASSISTANCE"
  | "MANAGE_ASSISTANCE"
  | "VIEW_OWN_DOCUMENTS"
  | "UPLOAD_OWN_DOCUMENT"
  | "DOWNLOAD_OWN_DOCUMENT"
  | "VIEW_PATIENT_DOCUMENTS"
  | "UPLOAD_PATIENT_DOCUMENT"
  | "DOWNLOAD_PATIENT_DOCUMENT"
  | "VIEW_LAB_DOCUMENTS"
  | "UPLOAD_LAB_DOCUMENTS"
  | "VIEW_DOCUMENT_METADATA"
  | "MANAGE_DOCUMENTS"
  | "VIEW_DOCUMENT_AUDIT"
  | "VIEW_SECURITY_EVENTS"
  | "MANAGE_OWN_SESSIONS"
  | "VIEW_OWN_CONSENT"
  | "MANAGE_OWN_CONSENT"
  | "REQUEST_PATIENT_CONSENT"
  | "VIEW_CONSENT_REGISTRY"
  | "ENABLE_MFA"
  | "VIEW_INTEGRATIONS"
  | "MANAGE_INTEGRATIONS"
  | "VIEW_INTEGRATION_LOGS"
  | "RETRY_INTEGRATION";

export const ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  patient: [
    "VIEW_OWN_PROFILE",
    "VIEW_OWN_MEDICAL_HISTORY",
    "VIEW_QUEUE",
    "REQUEST_ASSISTANCE",
    "VIEW_OWN_APPOINTMENTS",
    "BOOK_APPOINTMENT",
    "VIEW_OWN_DOCUMENTS",
    "UPLOAD_OWN_DOCUMENT",
    "DOWNLOAD_OWN_DOCUMENT",
    "MANAGE_OWN_SESSIONS",
    "VIEW_OWN_CONSENT",
    "MANAGE_OWN_CONSENT",
  ],
  doctor: [
    "VIEW_OWN_PROFILE",
    "VIEW_PATIENT",
    "VIEW_MEDICAL_HISTORY",
    "VIEW_QUEUE",
    "CALL_PATIENT",
    "CREATE_ENCOUNTER",
    "EDIT_ENCOUNTER",
    "COMPLETE_ENCOUNTER",
    "PRESCRIBE_MEDICATION",
    "REQUEST_CORRECTION",
    "ORDER_DIAGNOSTICS",
    "VIEW_DIAGNOSTIC_RESULTS",
    "REVIEW_DIAGNOSTIC_RESULTS",
    "ACKNOWLEDGE_CRITICAL_RESULT",
    "WRITE_DIAGNOSTIC_REPORT",
    "VIEW_PHARMACY_QUEUE",
    "VIEW_APPOINTMENT_SCHEDULE",
    "CHECK_IN_APPOINTMENT",
    "VIEW_PATIENT_DOCUMENTS",
    "UPLOAD_PATIENT_DOCUMENT",
    "DOWNLOAD_PATIENT_DOCUMENT",
    "MANAGE_OWN_SESSIONS",
    "REQUEST_PATIENT_CONSENT",
  ],
  clinical_staff: [
    "VIEW_OWN_PROFILE",
    "VIEW_PATIENT",
    "VIEW_QUEUE",
    "CALL_PATIENT",
    "ASSESS_PRIORITY",
    "REQUEST_OVERRIDE",
    "MANAGE_ASSISTANCE",
    "MANAGE_OWN_SESSIONS",
  ],
  receptionist: [
    "VIEW_OWN_PROFILE",
    "VIEW_PATIENT",
    "VIEW_QUEUE",
    "CALL_PATIENT",
    "REQUEST_OVERRIDE",
    "MANAGE_APPOINTMENTS",
    "CHECK_IN_APPOINTMENT",
    "VIEW_DOCUMENT_METADATA",
  ],
  lab_staff: [
    "VIEW_OWN_PROFILE",
    "VIEW_PATIENT",
    "VIEW_LAB_DASHBOARD",
    "VIEW_LAB_ORDERS",
    "COLLECT_SAMPLES",
    "ENTER_RESULTS",
    "SUBMIT_RESULTS",
    "FINALIZE_RESULTS",
    "SCHEDULE_DIAGNOSTICS",
    "PERFORM_DIAGNOSTIC_PROCEDURE",
    "VIEW_LAB_DOCUMENTS",
    "UPLOAD_LAB_DOCUMENTS",
  ],
  lab_reviewer: [
    "VIEW_OWN_PROFILE",
    "VIEW_PATIENT",
    "VIEW_LAB_DASHBOARD",
    "VIEW_LAB_ORDERS",
    "COLLECT_SAMPLES",
    "ENTER_RESULTS",
    "SUBMIT_RESULTS",
    "VERIFY_RESULTS",
    "VERIFY_DIAGNOSTIC_REPORT",
    "ACKNOWLEDGE_CRITICAL_RESULT",
    "SCHEDULE_DIAGNOSTICS",
    "PERFORM_DIAGNOSTIC_PROCEDURE",
    "WRITE_DIAGNOSTIC_REPORT",
    "VIEW_LAB_DOCUMENTS",
    "UPLOAD_LAB_DOCUMENTS",
  ],
  pharmacist: [
    "VIEW_OWN_PROFILE",
    "VIEW_PATIENT",
    "VIEW_MEDICAL_HISTORY",
    "VIEW_PHARMACY_DASHBOARD",
    "VIEW_PHARMACY_QUEUE",
    "DISPENSE_MEDICATION",
    "VIEW_PHARMACY_INVENTORY",
    "MANAGE_PHARMACY_STOCK",
  ],
  hospital_admin: [
    "VIEW_OWN_PROFILE",
    "VIEW_PATIENT",
    "VIEW_QUEUE",
    "CALL_PATIENT",
    "MANAGE_OPD",
    "MANAGE_DOCTOR",
    "MANAGE_STAFF",
    "MANAGE_DEPARTMENTS",
    "MANAGE_SERVICES",
    "MANAGE_QUEUE_CONFIG",
    "ASSIGN_STAFF_ROLES",
    "VIEW_OPERATIONAL_AUDIT",
    "MANAGE_HOSPITAL",
    "VIEW_REPORTS",
    "EXPORT_REPORTS",
    "VIEW_PHARMACY_QUEUE",
    "VIEW_PHARMACY_DASHBOARD",
    "VIEW_PHARMACY_INVENTORY",
    "VERIFY_RESULTS",
    "VERIFY_DIAGNOSTIC_REPORT",
    "VIEW_LAB_DASHBOARD",
    "VIEW_LAB_ORDERS",
    "MANAGE_APPOINTMENTS",
    "CHECK_IN_APPOINTMENT",
    "MANAGE_SCHEDULING",
    "ASSESS_PRIORITY",
    "REQUEST_OVERRIDE",
    "APPROVE_OVERRIDE",
    "VIEW_PRIORITY_AUDIT",
    "MANAGE_ASSISTANCE",
    "VIEW_DOCUMENT_METADATA",
    "MANAGE_DOCUMENTS",
    "VIEW_DOCUMENT_AUDIT",
    "VIEW_INTEGRATIONS",
    "MANAGE_INTEGRATIONS",
    "VIEW_INTEGRATION_LOGS",
    "RETRY_INTEGRATION",
  ],
  district_admin: [
    "VIEW_OWN_PROFILE",
    "VIEW_QUEUE",
    "VIEW_REPORTS",
    "VIEW_DISTRICT_DATA",
    "MANAGE_DISTRICT_SETTINGS",
    "PUBLISH_ANNOUNCEMENTS",
    "VIEW_DISTRICT_AUDIT",
    "EXPORT_REPORTS",
  ],
  state_admin: [
    "VIEW_OWN_PROFILE",
    "VIEW_QUEUE",
    "VIEW_REPORTS",
    "VIEW_DISTRICT_DATA",
    "VIEW_STATE_DATA",
    "EXPORT_REPORTS",
    "MANAGE_STATE_SETTINGS",
    "PUBLISH_STATE_ANNOUNCEMENTS",
    "VIEW_STATE_AUDIT",
    "MANAGE_STATE_USERS",
    "SCHEDULE_REPORTS",
    "VIEW_SYSTEM_HEALTH",
    "MANAGE_EMERGENCY_MODE",
    "VIEW_INTEGRATIONS",
    "MANAGE_INTEGRATIONS",
    "VIEW_INTEGRATION_LOGS",
    "RETRY_INTEGRATION",
  ],
};

export function roleHasPermission(role: UserRole | undefined, permission: Permission): boolean {
  if (!role) return false;
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}